# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6debd61874c93a916f711adb4a5e9ba5770b6a0324b858cd53e2f54fabd38454e1bb42858991cab5c8d2c733172d1f9a5c35a350a55b8de3f70e9753033bb3bf

test:
  secret_key_base: f428a373b0fb6dc5f158747797703b80325b9a43334b7db742210726e8ac01a5c74a9e2cc6b50666e0deb2e1a07cec9d09f07ee4a28d35a997b8d518034bc02f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
